vpc_cidr           = "10.0.0.0/16"
vpc_name           = "vpc"
subnet_cidr        = "10.0.1.0/24"
subnet_name        = "subnet"
igw_name           = "igw"
route_table_name   = "route-table"
sg_name            = "sg"
ami                = "ami-0453ec754f44f9a4a"
